import { NewsArticle, Match, TransferRumor, LeagueStanding, QuizQuestion } from './types';

export const mockArticles: NewsArticle[] = [
  {
    id: 'art-1',
    title: 'THE FINAL SHOWDOWN: Bellingham Leads Madrid into Champions League Final Clash',
    category: 'Analysis',
    tag: 'CHAMPIONS LEAGUE',
    summary: 'A dramatic brace from Jude Bellingham in the second half sends Real Madrid running to Munich as heavy favorites after overcoming a fierce tactical battle in the semi-finals.',
    content: 'In what will be remembered as an absolute classic, Jude Bellingham delivered a masterpiece performance. Intercepting a stray pass in the 68th minute, he drove through the heart of the opposition defense and uncoiled a thunderous strike in the top corner. Just ten minutes later, a precision cross from Vinicius Jr. met his forehead to secure the aggregate lead. Real Madrid has once again displayed their historic resilience on the grandest stage of European football.',
    date: '2026-06-20',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800',
    author: 'Daniel Cross',
    likes: 342,
    comments: 89,
    isTrending: true,
  },
  {
    id: 'art-2',
    title: 'EXCLUSIVE: Erling Haaland Agrees in Principle to Record-Breaking Contract Extension',
    category: 'Transfers',
    tag: 'CONTRACT NEWS',
    summary: 'The Norwegian marksman is set to committed his long-term future under Guardiola in a bumper deal that includes a astronomical release clause for overseas clubs.',
    content: 'Manchester City have reached an agreement in principle with Erling Haaland for a new five-year contract extension. The terms are rumored to make him the highest-paid player in Premier League history. Crucially, the agreement contains a tailored €180 million release clause active from the summer of 2028, offering City temporary security while giving Haaland continued agency over his career trajectory. Negotiations concluded amicably after months of internal boardroom discussions.',
    date: '2026-06-19',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?auto=format&fit=crop&q=80&w=800',
    author: 'Sophia Vance',
    likes: 512,
    comments: 114,
    isTrending: true,
  },
  {
    id: 'art-3',
    title: 'Tactical Breakdown: How Arsenal Overwhelmed Liverpool Out of Possession',
    category: 'Analysis',
    tag: 'TACTICAL MASTERCLASS',
    summary: 'An inside look at Mikel Arteta’s high-pressing structure that completely severed the passing lanes to Mohamed Salah, forcing errors in central zones.',
    content: 'Arteta deployed a highly disciplined mid-block press that transformed into an asymmetric 4-4-2 out of possession. Declan Rice’s positioning was vital, pressing high onto Liverpool’s primary progressor while Gabriel Martinelli tucked inside to shadow-mark the deep midfielder. By completely choking the access lines to Salah on the right half-space, Liverpool were forced to carry the ball through congested central lanes, resulting in 14 turnovers in their own half. A true systemic victory.',
    date: '2026-06-18',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&q=80&w=800',
    author: 'Mark Sterling',
    likes: 231,
    comments: 42,
  },
  {
    id: 'art-4',
    title: 'Major Outback: Barcelona Captain Suffers Grade-2 Hamstring Strain in Training',
    category: 'News',
    tag: 'BARCELONA',
    summary: 'The midfelder was forced to withdraw from training session and is expected to miss the upcoming crucial El Clásico as medical scans confirm three-week layoff.',
    content: 'Barcelona’s title charge has suffered a devastating blow with news that their captain has picked up a grade-2 hamstring tear in training. He pulled up clutching the back of his left leg during a transition drill. Clinical scans performed in the afternoon confirmed a minimum 3-week recovery times. He will miss not only El Clásico but also both legs of the crucial Copa del Rey quarter-finals, leaving Hansi Flick with a major selection headache in midfield.',
    date: '2026-06-17',
    readTime: '2 min read',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    author: 'Enric Torres',
    likes: 189,
    comments: 73,
  },
  {
    id: 'art-5',
    title: 'The Unstoppable Rise of Florian Wirtz: Why Europe’s Giants are Lining Up',
    category: 'Analysis',
    tag: 'SCOUTING SPOTLIGHT',
    summary: 'A deep-dive exploration into Leverkusen’s talismanic number 10, highlighting his unique spatial orientation and incredible playmaking efficiency.',
    content: 'Florian Wirtz continues to defy standard metrics. Playing under Xabi Alonso, his spatial awareness in tight half-spaces has matured into world-class tier. Statistically, he ranks in the 99th percentile for progressive carries, and his progressive pass receipt metric indicates that he is the focal engine of Bayer Leverkusen. "I just search for the gaps," Wirtz remarked in our exclusive chat. With Real Madrid and Bayern Munich positioning themselves for next summer, we breakdown his key metrics.',
    date: '2026-06-16',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1579952365116-61317f0501cd?auto=format&fit=crop&q=80&w=800',
    author: 'Julian Brandt',
    likes: 420,
    comments: 98,
  },
  {
    id: 'art-6',
    title: 'World Cup 2026: Tactical Outlook of National Teams Preparing for the Global Stage',
    category: 'World Cup',
    tag: 'INTERNATIONAL TEAM NEWS',
    summary: 'An exclusive review of the preparation setups, team cohesion matrices, and tactical frameworks adopted by the worlds leading national squads.',
    content: 'The countdown to FIFA World Cup 2026 is officially on. Elite coaches are tuning their systems to withstand intensive tournament schedules. From defense-first blocks to relentless fluid pressing sequences, we evaluate the readiness of national teams including Argentina, France, and Brazil, examining key statistics that could define who raises the ultimate trophy.',
    date: '2026-06-15',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800',
    author: 'Daniel Cross',
    likes: 624,
    comments: 147,
  },
  {
    id: 'art-7',
    title: 'Premier League Clubs Strategy: Crucial Pre-season Changes in Top-flight Football',
    category: 'Clubs',
    tag: 'DOMESTIC LEAGUES',
    summary: 'How elite clubs are restructuring their rosters to deal with increased match load and tactical developments in domestic hierarchies.',
    content: 'Clubs across Europe are adapting swiftly to high-octane requirements. Tactical analysis reveals a collective shift towards asymmetrical transitions, forcing clubs like Arsenal and Manchester City to invest heavily in versatile hybrid full-backs. We dissect current statistical configurations of major European clubs to predict next terms early frontrunners.',
    date: '2026-06-14',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&q=80&w=800',
    author: 'Sophia Vance',
    likes: 310,
    comments: 54,
  },
  {
    id: 'art-8',
    title: 'The Art of the Double Pivot: Inside Modern Midfield Configurations',
    category: 'Analysis',
    tag: 'TACTICS 101',
    summary: 'An depth study of why elite managers prefer paired defensive midfielders in contemporary football schemes.',
    content: 'The double pivot is no longer just a defensive shield. In modern possession architectures, it serves as the secondary launchpad. By having two technical operators operating parallel to one another, clubs gain security against central counter-pressing and form reliable passing triangles with center-backs and inverted fullbacks.',
    date: '2026-06-13',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800',
    author: 'Mark Sterling',
    likes: 245,
    comments: 39,
  },
  {
    id: 'art-9',
    title: 'Expected Goals (xG) Demystified: The Metric Changing Football Recruitment',
    category: 'Analysis',
    tag: 'DATA SCIENCE',
    summary: 'How clubs are discarding traditional goal tallies in favor of high-fidelity predictive performance metrics.',
    content: 'Goalscoring has always been subject to variance. Expected Goals (xG) allows analysts to filter out luck and evaluate the long-term repeatability of a striker’s output. By weighting shot location, defensive pressure, and delivery type, we uncover who is genuinely elite and who is merely enjoying a hot streak.',
    date: '2026-06-12',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800',
    author: 'Mark Sterling',
    likes: 412,
    comments: 88,
  },
  {
    id: 'art-10',
    title: 'The High-Line Defensive Risk: Why the Boldest Teams Win Big and Lose Harder',
    category: 'Analysis',
    tag: 'TACTICS 101',
    summary: 'Evaluating the narrow margins of error involved in defending forty yards away from your own goal line.',
    content: 'Defending high up the pitch requires supreme defensive synchronization. A fraction of a second delay in pressure on the ball carrier exposes the backline to lethal runs. Yet, teams like Barcelona and Aston Villa continue to reap massive rewards by compressing the pitch and catching opponents offside.',
    date: '2026-06-11',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    author: 'Mark Sterling',
    likes: 290,
    comments: 49,
  },
  {
    id: 'art-11',
    title: 'Serie A Midfield Maestro Heavily Linked with Blockbuster Newcastle Move',
    category: 'Transfers',
    tag: 'TRANSFER CENTER',
    summary: 'Reports in Italy claim Newcastle scouts have submitted a formal proposal for the league’s most consistent deep playmaker.',
    content: 'Newcastle United are looking to solidify their engine room with elite technical control. Sources suggest a €65m bids has been prepared for the Italian controller, who is keen to test himself in the physical arena of the Premier League. Terms are expected to advance rapidly.',
    date: '2026-06-10',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?auto=format&fit=crop&q=80&w=800',
    author: 'Sophia Vance',
    likes: 350,
    comments: 67,
  },
  {
    id: 'art-12',
    title: 'La Liga Wonderkid Attracts Keen Inquiries From Top-Three English Clubs',
    category: 'Transfers',
    tag: 'TRANSFER CENTER',
    summary: 'A bidding war is brewing for Spain’s latest teen sensation currently excelling in his breakout top-flight season.',
    content: 'Scouts from Arsenal, Liverpool, and Chelsea have all registered official interest in the 17-year-old winger. With a buyout clause set at €50m, clubs see him as a generational market opportunity before his valuation reaches astronomical heights next year.',
    date: '2026-06-09',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?auto=format&fit=crop&q=80&w=800',
    author: 'Sophia Vance',
    likes: 480,
    comments: 92,
  },
  {
    id: 'art-13',
    title: 'Ligue 1 Powerhouse Midfielder Agrees Terms With Bayern Munich',
    category: 'Transfers',
    tag: 'TRANSFER CENTER',
    summary: 'The physical powerhouse is set to switch to the Bundesliga giants for a reported fee of €45 million.',
    content: 'Bayern Munich have secured their primary midfield target. The Frenchman, known for his relentless ball recovery and progressive carries, has signed a four-year contract. Under the guidance of Munich’s tactical setup, he is poised to become the cornerstone of their midfield.',
    date: '2026-06-08',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?auto=format&fit=crop&q=80&w=800',
    author: 'Sophia Vance',
    likes: 310,
    comments: 41,
  },
  {
    id: 'art-14',
    title: 'Free Agent Bargains: Five Top-Class Players Up For Grabs This Summer',
    category: 'Transfers',
    tag: 'TRANSFER CENTER',
    summary: 'Our breakdown of elite out-of-contract stars who represent zero-transfer-fee opportunities for shrewd clubs.',
    content: 'The free agent market has never been this star-studded. Shrewd sporting directors are already queuing up to offer contract proposals to established internationals looking to start fresh. We analyze their wage expectations and prospective tactical fits in detailed profiles.',
    date: '2026-06-07',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?auto=format&fit=crop&q=80&w=800',
    author: 'Sophia Vance',
    likes: 290,
    comments: 55,
  },
  {
    id: 'art-15',
    title: 'Bundesliga Goal Machine Tops Chelsea Scout Lists For Next Transfer Window',
    category: 'Transfers',
    tag: 'TRANSFER CENTER',
    summary: 'With Stamford Bridge seeking direct central firepower, the clinical striker emerges as the outstanding candidate.',
    content: 'Chelsea are scouring Europe for a ruthless forward. After netting 24 goals in Germany this term, the Austrian spearhead fits the profile perfectly. Initial discussions with representatives indicate a strong willingness to discuss a move to the English capital.',
    date: '2026-06-06',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?auto=format&fit=crop&q=80&w=800',
    author: 'Sophia Vance',
    likes: 560,
    comments: 130,
  },
  {
    id: 'art-16',
    title: 'Inter Milan Clinch Historic Serie A Championship In Dramatic Derby Victory',
    category: 'News',
    tag: 'SERIE A',
    summary: 'A tactical masterclass on the grandest stage of the Milan derby hands Inter their 20th league title.',
    content: 'Inter Milan have secured the Scudetto with several matches to spare. A brilliant tactical setups by Inzaghi choked down Milan’s wing threat, while Martinez’s clever movement in deep spaces carved open the defense. The city belongs to the Nerazzurri tonight in wild celebrations.',
    date: '2026-06-05',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    author: 'Enric Torres',
    likes: 670,
    comments: 112,
  },
  {
    id: 'art-17',
    title: 'UEFA Confirms Exciting Structural Format Changes To Champions League Groups',
    category: 'News',
    tag: 'CHAMPIONS LEAGUE',
    summary: 'A single league-phase system will replace traditional groups, generating more high-stakes matches early in the term.',
    content: 'In an official statement, UEFA detailed the expansion of Europe’s premier club competition. Moving away from the classic groups, 36 clubs will battle in a unified league table, ensuring top teams face off directly right from the start. Football fans can expect high drama weekly.',
    date: '2026-06-04',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    author: 'Enric Torres',
    likes: 420,
    comments: 87,
  },
  {
    id: 'art-18',
    title: 'Domestic Golden Boot Race Reaches Dramatic Final-Day Thriller',
    category: 'News',
    tag: 'INDIVIDUAL HONORS',
    summary: 'Two strikers remain locked on equal goals heading into the highly anticipated season closer on Sunday.',
    content: "It's the tightest top-scorer contest in a decade. With both talismanic strikers sitting on 26 goals, the final 90 minutes of the season will settle who wins the prestigious Golden Boot. Tactical systems are being optimized to feed their respective main targets for ultimate victory.",
    date: '2026-06-03',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    author: 'Enric Torres',
    likes: 380,
    comments: 64,
  },
  {
    id: 'art-19',
    title: 'Official International Friendly Fixtures Calendar Fully Finalized',
    category: 'News',
    tag: 'INTERNATIONALS',
    summary: 'Fifa confirms full array of autumn direct preparations for top-flight national teams.',
    content: 'The international federation has rubber-stamped the friendly calendar. Elite heavyweights will face off in marquee friendly matches this autumn, providing vital preparation. Coaches will use the opportunity to test tactical layouts and blood promising youngsters into the senior squads.',
    date: '2026-06-02',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    author: 'Enric Torres',
    likes: 210,
    comments: 31,
  },
  {
    id: 'art-20',
    title: 'Legendary Goalkeeper Formally Announces Retirement From Professional Sport',
    category: 'News',
    tag: 'RETIREMENT NEWS',
    summary: 'After twenty-two glorious years in top-flight nets, the iconic gloveman calls time on an illustrious career.',
    content: 'An emotional farewell press conference confirmed the news. The 40-year-old custodian, decorated with three champion medals and a world title, is hanging up his gloves at the end of June. Tributes are pouring in from peers worldwide celebrating his extraordinary shot-stopping legacy.',
    date: '2026-06-01',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    author: 'Enric Torres',
    likes: 850,
    comments: 198,
  }
];

export const mockMatches: Match[] = [
  {
    id: 'match-1',
    homeTeam: 'Arsenal',
    homeLogo: '🔴',
    awayTeam: 'Man City',
    awayLogo: '🔵',
    homeScore: 2,
    awayScore: 2,
    status: 'LIVE',
    league: 'Premier League',
    minute: 74,
    stadium: 'Emirates Stadium, London',
    events: [
      { type: 'goal', player: 'E. Haaland', minute: 18, team: 'away', detail: 'Assist: K. De Bruyne' },
      { type: 'goal', player: 'B. Saka', minute: 34, team: 'home', detail: 'Penalty kick' },
      { type: 'card_yellow', player: 'Rodri', minute: 41, team: 'away' },
      { type: 'goal', player: 'K. Havertz', minute: 56, team: 'home', detail: 'Header from corner' },
      { type: 'goal', player: 'Phil Foden', minute: 69, team: 'away', detail: 'Stunning curler from distance' },
      { type: 'card_yellow', player: 'William Saliba', minute: 71, team: 'home' }
    ]
  },
  {
    id: 'match-2',
    homeTeam: 'Real Madrid',
    homeLogo: '⚪',
    awayTeam: 'Barcelona',
    awayLogo: '🔴🔵',
    homeScore: 3,
    awayScore: 2,
    status: 'FT',
    league: 'La Liga',
    stadium: 'Santiago Bernabéu, Madrid',
    events: [
      { type: 'goal', player: 'Robert Lewandowski', minute: 12, team: 'away' },
      { type: 'goal', player: 'Vinicius Jr.', minute: 26, team: 'home', detail: 'Penalty shot' },
      { type: 'card_yellow', player: 'Pedri', minute: 31, team: 'away' },
      { type: 'goal', player: 'Lamine Yamal', minute: 54, team: 'away' },
      { type: 'goal', player: 'Fede Valverde', minute: 73, team: 'home', detail: 'Assist: Bellingham' },
      { type: 'goal', player: 'Jude Bellingham', minute: 90, team: 'home', detail: 'Stoppage time winner!' }
    ]
  },
  {
    id: 'match-3',
    homeTeam: 'Liverpool',
    homeLogo: '🔴⚽',
    awayTeam: 'Chelsea',
    awayLogo: '🔵🦁',
    homeScore: 0,
    awayScore: 0,
    status: 'UPCOMING',
    league: 'Premier League',
    date: 'Tomorrow, 17:30',
    stadium: 'Anfield, Liverpool',
    events: []
  },
  {
    id: 'match-4',
    homeTeam: 'Bayern Munich',
    homeLogo: '🔴🔴',
    awayTeam: 'Dortmund',
    awayLogo: '🟡⚫',
    homeScore: 4,
    awayScore: 1,
    status: 'FT',
    league: 'Bundesliga',
    stadium: 'Allianz Arena, Munich',
    events: [
      { type: 'goal', player: 'Harry Kane', minute: 4, team: 'home' },
      { type: 'goal', player: 'Jamal Musiala', minute: 21, team: 'home' },
      { type: 'goal', player: 'Harry Kane', minute: 45, team: 'home' },
      { type: 'goal', player: 'Serhou Guirassy', minute: 61, team: 'away' },
      { type: 'goal', player: 'Leroy Sané', minute: 82, team: 'home' }
    ]
  },
  {
    id: 'match-5',
    homeTeam: 'Paris SG',
    homeLogo: '🗼',
    awayTeam: 'Marseille',
    awayLogo: '🔵⚪',
    homeScore: 2,
    awayScore: 0,
    status: 'FT',
    league: 'Ligue 1',
    stadium: 'Parc des Princes, Paris',
    events: [
      { type: 'goal', player: 'Ousmane Dembélé', minute: 31, team: 'home' },
      { type: 'card_red', player: 'Harit', minute: 54, team: 'away', detail: 'Server tackle' },
      { type: 'goal', player: 'Bradley Barcola', minute: 75, team: 'home' }
    ]
  }
];

export const mockTransferRumors: TransferRumor[] = [
  {
    id: 'tr-1',
    player: 'Alphonso Davies',
    position: 'Left-Back',
    fromTeam: 'Bayern Munich',
    fromLogo: '🇩🇪',
    toTeam: 'Real Madrid',
    toLogo: '🇪🇸',
    fee: 'Free Transfer (Contract expiry)',
    probability: 92,
    source: 'Fabrizio Romano',
    status: 'Advanced',
  },
  {
    id: 'tr-2',
    player: 'Viktor Gyökeres',
    position: 'Striker',
    fromTeam: 'Sporting CP',
    fromLogo: '🇵🇹',
    toTeam: 'Arsenal',
    toLogo: '🇬🇧',
    fee: '€100,000,000 (Release clause)',
    probability: 78,
    source: 'The Athletic',
    status: 'Rumor',
  },
  {
    id: 'tr-3',
    player: 'Kylian Mbappé',
    position: 'Forward',
    fromTeam: 'Paris SG',
    fromLogo: '🇫🇷',
    toTeam: 'Real Madrid',
    toLogo: '🇪🇸',
    fee: 'Free Transfer',
    probability: 100,
    source: 'Official Announcement',
    status: 'Confirmed',
  },
  {
    id: 'tr-4',
    player: 'Nico Williams',
    position: 'Winger',
    fromTeam: 'Athletic Bilbao',
    fromLogo: '🇪🇸',
    toTeam: 'Barcelona',
    toLogo: '🇪🇸',
    fee: '€58,000,000',
    probability: 65,
    source: 'Gerard Romero',
    status: 'Rumor',
  },
  {
    id: 'tr-5',
    player: 'Trent Alexander-Arnold',
    position: 'Right-Back',
    fromTeam: 'Liverpool',
    fromLogo: '🇬🇧',
    toTeam: 'Real Madrid',
    toLogo: '🇪🇸',
    fee: 'Free Transfer',
    probability: 84,
    source: 'Chiringuito TV',
    status: 'Advanced',
  }
];

export const leagueTables: Record<string, LeagueStanding[]> = {
  'Premier League': [
    { rank: 1, team: 'Arsenal', logo: '🔴', played: 30, won: 22, drawn: 5, lost: 3, points: 71, goalDiff: '+42' },
    { rank: 2, team: 'Man City', logo: '🔵', played: 30, won: 21, drawn: 6, lost: 3, points: 69, goalDiff: '+39' },
    { rank: 3, team: 'Liverpool', logo: '🔴⚽', played: 30, won: 20, drawn: 8, lost: 2, points: 68, goalDiff: '+35' },
    { rank: 4, team: 'Aston Villa', logo: '🦁', played: 31, won: 18, drawn: 5, lost: 8, points: 59, goalDiff: '+18' },
    { rank: 5, team: 'Tottenham', logo: '⚪🐓', played: 30, won: 17, drawn: 6, lost: 7, points: 57, goalDiff: '+15' },
    { rank: 6, team: 'Man United', logo: '😈', played: 30, won: 15, drawn: 3, lost: 12, points: 48, goalDiff: '0' },
    { rank: 7, team: 'Chelsea', logo: '🔵🦁', played: 30, won: 13, drawn: 7, lost: 10, points: 46, goalDiff: '+4' }
  ],
  'La Liga': [
    { rank: 1, team: 'Real Madrid', logo: '⚪', played: 30, won: 23, drawn: 6, lost: 1, points: 75, goalDiff: '+46' },
    { rank: 2, team: 'Barcelona', logo: '🔴🔵', played: 30, won: 20, drawn: 7, lost: 3, points: 67, goalDiff: '+31' },
    { rank: 3, team: 'Girona', logo: '🔴⚪', played: 30, won: 20, drawn: 5, lost: 5, points: 65, goalDiff: '+28' },
    { rank: 4, team: 'Atlético Madrid', logo: '🔴⚪🔵', played: 30, won: 18, drawn: 4, lost: 8, points: 58, goalDiff: '+21' },
    { rank: 5, team: 'Athletic Bilbao', logo: '🔴⚪', played: 30, won: 16, drawn: 8, lost: 6, points: 56, goalDiff: '+19' }
  ],
  'Serie A': [
    { rank: 1, team: 'Inter Milan', logo: '🔵⚫', played: 30, won: 25, drawn: 4, lost: 1, points: 79, goalDiff: '+57' },
    { rank: 2, team: 'AC Milan', logo: '🔴⚫', played: 30, won: 20, drawn: 5, lost: 5, points: 65, goalDiff: '+23' },
    { rank: 3, team: 'Juventus', logo: '⚪⚫', played: 30, won: 17, drawn: 8, lost: 5, points: 59, goalDiff: '+19' },
    { rank: 4, team: 'Bologna', logo: '🔵🔴', played: 30, won: 16, drawn: 9, lost: 5, points: 57, goalDiff: '+17' },
    { rank: 5, team: 'AS Roma', logo: '🟡🔴', played: 30, won: 15, drawn: 7, lost: 8, points: 52, goalDiff: '+15' }
  ]
};

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q-1',
    question: 'Which country has won the most FIFA World Cup titles?',
    options: ['Germany', 'Italy', 'Brazil', 'Argentina'],
    correctIndex: 2,
    trivia: 'Brazil has won the tournament five times (1958, 1962, 1970, 1994, 2002).'
  },
  {
    id: 'q-2',
    question: 'Who is the all-time leading goal scorer in UEFA Champions League history?',
    options: ['Lionel Messi', 'Cristiano Ronaldo', 'Robert Lewandowski', 'Raúl'],
    correctIndex: 1,
    trivia: 'Cristiano Ronaldo holds the record with 140 Champions League goals scored with Man Utd, Real Madrid, and Juventus.'
  },
  {
    id: 'q-3',
    question: 'Select the club that achieved the legendary "Invincibles" Premier League season in 2003/04.',
    options: ['Manchester United', 'Chelsea', 'Arsenal', 'Manchester City'],
    correctIndex: 2,
    trivia: 'Arsenal went unbeaten for the entire 2003/04 season under Arsène Wenger, winning 26 and drawing 12.'
  },
  {
    id: 'q-4',
    question: 'Which player holds the record for most assists in a single Premier League season (20, shared)?',
    options: ['Kevin De Bruyne & Thierry Henry', 'Cesc Fàbregas & Mesut Özil', 'Ryan Giggs & David Beckham', 'Frank Lampard & Eden Hazard'],
    correctIndex: 0,
    trivia: 'Thierry Henry racked up 20 assists in 2002/03, and Kevin De Bruyne matched it in 2019/20.'
  },
  {
    id: 'q-5',
    question: 'Which African nation became the first to reach the semi-finals of a FIFA World Cup in 2022?',
    options: ['Cameroon', 'Senegal', 'Nigeria', 'Morocco'],
    correctIndex: 3,
    trivia: 'Morocco made history in Qatar 2022, defeating Spain and Portugal in the knockout stage to reach the semi-finals.'
  }
];
